[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.13",
    "pydantic-settings>=2.10.0",
    "uvicorn>=0.34.3",
    "python-multipart>=0.0.9",
    "python-dotenv>=1.0.0",
]
